services:
  # 샤드 1: 워크스페이스 A-H
  postgres-shard1:
    image: postgres:15
    container_name: slack_clone_db_shard1
    restart: unless-stopped
    environment:
      POSTGRES_DB: slack_clone_shard1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_shard1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 샤드 2: 워크스페이스 I-P  
  postgres-shard2:
    image: postgres:15
    container_name: slack_clone_db_shard2
    restart: unless-stopped
    environment:
      POSTGRES_DB: slack_clone_shard2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_shard2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 샤드 3: 워크스페이스 Q-Z
  postgres-shard3:
    image: postgres:15
    container_name: slack_clone_db_shard3
    restart: unless-stopped
    environment:
      POSTGRES_DB: slack_clone_shard3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_shard3:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_shard1:
    driver: local
  postgres_data_shard2:
    driver: local
  postgres_data_shard3:
    driver: local 